### ISSUE TITLE
Section 07 : Asso

### ISSUE THREAD

**Issue by dnsfng** [LeoGourven/echap#14]
- [ ] Positionner cet élément en arrière plan pour qu'il apparaissent sous les infos pratiques au scroll (comme le footer sur dataveyes.com)
- [x] L'icone des doigts en l'air est coupée

**Comment by LeoGourven** [comment]
@dnsfng Sur le site de DV c'est géré avec le footer en fixed et un padding-bottom sur le reste du contenu.

Là le problème c'est que la hauteur du bloc est variable.
