### ISSUE TITLE
Hover

### ISSUE THREAD

**Issue by dnsfng** [LeoGourven/echap#18]
Mon cher Léo,

J'ai envie de faire un truc pour les hover et j'ai peur que ça me prenne plus de temps à coder avec ton javascript super mega ecma script 6.

En gros, l'idée serait de gérer les interactions pour que lorsqu'on survol un texte (ou icone), ça nous change la couleur via une liste de teinte prédéfinies.

Ce dont j'ai besoin
- au survol sur un élément identifié avec une `class` ou un `data-…`
- faire un random sur des valeurs de couleurs (prédéfinies)
- appliquer un style inline du genre `style="color:#AAAAAA`ou AAAAAA est la couleur aléatoire
- l'enlever lorsqu'on sort du survol (c'est sur ce point là que j'ai un doute, mais j'y ai pas bcq réfléchi)

Ça te semble compliqué ?

**Comment by LeoGourven** [comment]
@dnsfng Je ne vois rien de compliqué là dedans. Je peux mettre ça en place, tu le souhaites sur quel élément ?

**Comment by dnsfng** [comment]
En fait je souhaiterais l'appliquer à n'importe quel élément dont je définis une class.

Ouais c'est pas compliqué c'est juste que j'ai pas lu la doc de ton domquery.
Je sais pas si y a un équivalent d'un mouseOut.

Si tu peux le faire sur la class 'rainbow' ça serait top !
(si je survole un élément .rainbow ça lui attribue une couleur de texte choisie aléatoirement dans la liste)

**Comment by LeoGourven** [comment]
@dnsfng C'est fait !

La liste de couleur est dans app.js (variable colors) et la classe à appliquer est la ".rainbow"
