### ISSUE TITLE
Section 03 : édito

### ISSUE THREAD

**Issue by dnsfng** [LeoGourven/echap#9]
- [x] Vérifier la position des éléments, les marges, les typo, l'interlignage
- [x] Mieux positionner le visage selon la grille
- [x] Ajouter la légende de l'illustration (cf. maquette)
- [x] Prévoir le parallax sur l'illustration

**Comment by LeoGourven** [comment]
@dnsfng J'ai testé un parallax fait maison sur l'illustration. Il est configurable (dans la variable "illuScale", j'ai mis un peu de doc au dessus. Tu penses que c'est bon je pars là dessus sur le reste aussi ?

**Comment by dnsfng** [comment]
Y a moyen de faire varier un `transform : translate`ou `translate3d` ?
Je pense que ça bousille les perf le background position et puis ça provoque des problèmes de clipping vu que le background-image est toujours coincé dans le conteneur courant.

**Comment by LeoGourven** [comment]
Yes tu as raison !

**Comment by LeoGourven** [comment]
@dnsfng C'est fait
